# Generated by Django 5.2.4 on 2026-02-24 09:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_mockquestion_mockattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockattempt',
            old_name='date',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='mockattempt',
            name='category',
            field=models.CharField(default='DSA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mockattempt',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mockattempt',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mockattempt',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mockquestion',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mockquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockquestion',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codingpractice',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='mockquestion',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mockquestion',
            name='option1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mockquestion',
            name='option2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mockquestion',
            name='option3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mockquestion',
            name='option4',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.mockattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.mockquestion')),
            ],
        ),
    ]
